name: "🚫 Opt-Out Request / 拒绝抓取请求"
description: "Submit website opt-out request / 提交网站拒绝抓取请求"
title: "[Opt-Out Request] Please enter your website domain here / 请在此处填写您的网站域名"
labels: ["opt-out"]
body:
  - type: markdown
    attributes:
      value: |
        Please carefully fill in the following information. We will add your domain to the avoid-crawl list after verification.
        请仔细填写以下信息，我们将在核实后把您的域名加入避免抓取列表。

        **Note:** This is an open source project, updates and releases require certain cycles. Thank you for your understanding and cooperation.
        **注意：** 本项目是开源项目，更新和发布需要一定的周期，感谢您的理解与配合。

  - type: input
    id: domain
    attributes:
      label: "Website Domain / 网站域名"
      description: "Please enter the complete domain name you wish to opt-out / 请输入您要申请拒绝抓取的完整域名"
      placeholder: "example.com"
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: "Contact Email / 联系人邮箱"
      description: "For identity verification when necessary. We will strictly protect your privacy. / 用于必要时核实身份，我们将严格保护您的隐私"
      placeholder: "contact@example.com"
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: "Additional Information / 其他说明"
      description: "Please provide any additional information that may help us process your request / 请提供任何可能有助于我们处理您请求的额外信息"
      placeholder: "Example: Any special requirements or additional context about your request / 例如：任何特殊要求或关于您请求的额外背景信息"

  - type: checkboxes
    id: terms
    attributes:
      label: "Confirmation Statement / 确认声明"
      description: "Please confirm the following statements / 请确认以下声明"
      options:
        - label: "I confirm that I am the legal owner or authorized representative of this domain / 我确认我是该域名的合法所有者或授权代表"
          required: true
        - label: "I understand this is an open source project and updates require certain processing cycles / 我理解这是一个开源项目，更新需要一定的处理周期"
          required: true
        - label: "I agree to have my request processed according to the project procedures / 我同意按照项目流程处理我的请求"
          required: true
